name: 构建docker镜像

on: push

jobs:
  job1:
    name: 构建docker镜像
    runs-on: ubuntu-20.04
    steps:
      # - name: 检出项目nichuanfang
      #   uses: actions/checkout@v3.5.2

      # - name: 检出nichuanfang/docker
      #   uses: actions/checkout@v3.5.2
      #   with:
      #     repository: nichuanfang/docker
      #     path: docker
      #     ref: master
      #     token: ${{ secrets.GH_TOKEN }}

      - name: 查看python版本
        run: python -V

      - name: 查看python路径
        run: which python

      - name: 查看pip版本
        run: pip -V

      - name: 查看pip路径
        run: which pip

      - name: 查看docker版本
        run: docker version

      - name: 查看docker-compose版本
        run: docker-compose version
