name: 构建docker镜像

on: push

jobs:
  job1:
    name: 构建docker镜像
    runs-on: ubuntu-20.04
    steps:
      # $GITHUB_WORKSPACE   =  /home/runner/work/crawler/crawler
      - name: 查看$GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE

      - name: 检出项目nichuanfang
        uses: actions/checkout@v3.5.2
        with:
          repository: nichuanfang/crawler
          path: crawler
          ref: master
          token: ${{ secrets.GH_TOKEN }}

      - name: 检出nichuanfang/docker
        uses: actions/checkout@v3.5.2
        with:
          repository: nichuanfang/docker
          path: docker
          ref: master
          token: ${{ secrets.GH_TOKEN }}

      - name: 确认crawler路径
        run: ls $GITHUB_WORKSPACE/crawler

      - name: 确认docker路径
        run: ls $GITHUB_WORKSPACE/docker
